---

- name: Download cephadm script
  get_url:
    url: "https://download.ceph.com/rpm-18.2.0/el9/noarch/cephadm"
    dest: "/root"

- name: Changing perm of "/root/cephadm", adding "+x"
  file: dest="/root/cephadm" mode=a+x

- name: Add Ceph repository
  command: >
    /root/cephadm add-repo --release reef

- name: Update Repository
  apt:
    update_cache: yes
  

- name: Install Ceph
  command: /root/cephadm install

- name: remove cephadm binary
  command: rm -rf /root/cephadm


- name: Include encrypted variables
  include_vars:
    file: vars/secret.yml
    name: secret

- name: Set fact for mon_ip
  set_fact:
    mon_ip: "{{ ansible_default_ipv4.address }}"


- name: Bootstrap Ceph cluster using cephadm
  command: "cephadm bootstrap --mon-ip {{ mon_ip }} --initial-dashboard-user {{ secret['vault-server-username'] }} --initial-dashboard-password {{ secret['vault-server-password'] }} --allow-overwrite"
  register: ceph_bootstrap_result
  when: ansible_hostname == "ceph1"


- name: Generate SSH key pair
  openssh_keypair:
    path: /root/.ssh/id_rsa

- name: Copy public key to hosts
  expect:
    command: ssh-copy-id root@{{ item }}
    responses:
      "password": "{{ secret['vm'] }}"
  loop:
    - 172.31.112.118
    - 172.31.112.119

  when: "'{{ inventory_hostname }}' == 'ceph1'"



- name: Copy ceph.pub
  expect:
    command: ssh-copy-id -f -i /etc/ceph/ceph.pub root@{{ item }}
    responses:
      "password": "{{ secret['vm'] }}"
  loop:
    - 172.31.112.118
    - 172.31.112.119

  when: "'{{ inventory_hostname }}' == 'ceph1'"

- name: install ceph-common
  command: cephadm install ceph-common



    #- name: adding host to cluster
    #  command: ceph orch host add {{ inventory_hostname }} {{ ansible_default_ipv4.address }} --labels _admin
    #  when: "'{{ inventory_hostname }}' == 'ceph2' or '{{ inventory_hostname }}' == 'ceph3'"
    #
    #
    #
    #- name: waiting for adding hosts
    #  command: sleep 600
    #
    #- name: adding osd to cluster
    #  command: ceph orch apply osd --all-available-devices




